services:
  app:
    image: ghcr.io/pschlo/posthub:latest
    pull_policy: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      POSTHUB_DB_HOST: database
      POSTHUB_DB_PORT: 3306
      POSTHUB_DB_NAME: posthub
      POSTHUB_DB_USER: posthub
      POSTHUB_DB_PASSWORD: posthub
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: posthub
      MARIADB_USER: posthub
      MARIADB_PASSWORD: posthub
      MARIADB_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

volumes:
  database-data:
